(function($){$.fn.game=function(iStartLevel,iMaxLevel,iDir,iImages){var detectTap=false;var gBalls;var gBallsImages=iImages;var gBallsWidth;var gBallsHeight;var gAllBallsWidth;var gameDurationSeconds;var gCountPayerSquares=0;var gCountGoodPayerBalls=0;var gPlayerWin=false;var gScore=0;var gLevel=iStartLevel;var gTotalScore=60;var gTotalLevel=iMaxLevel;var arrayRandom=new Array();var arrayShuffle=new Array();var arrayPlayer=new Array();var arrayPlayerIds=new Array();var pathImages=gBaseUrl+"../jpg/abaco/"+iDir;var lang=gLang.split("-")[0];var gStrYouWin="*********&nbsp;&nbsp;Congrats!!!&nbsp;&nbsp;**********";var gStrYouWinLevel="Congrats!  You win!";var gStrYouWinTxt="You have successfully completed all levels!";var gStrYouWinLevelTxt="Click on CONTINUE to go to the next level...";var gStrStart="START";var gStrLevel="Level";var gStrScore="Score";var gStrLook="Look at the series of balls and try to remember it";var gStrMsgPlayer="You have to position the balls on the abacus by sorting them in the correct order";var gStrClickStart="Click on START button to play";var gStrTitleGame="Game of the Abacus";var gStrCheck="CHECK";var gStrTryAgain="TRY AGAIN";var gStrPlayAgain="PLAY AGAIN";var gStrContinue="CONTINUE";var gStrLost="You lost!";var gStrBallFound="ball correctly positioned";var gStrBallsFound="balls correctly positioned";if(lang=='es'){gStrYouWin="*********&nbsp;&nbsp;Felicitaciones!!!&nbsp;&nbsp;**********";gStrYouWinLevel="Felicitaciones!  Ha ganado!";gStrYouWinTxt="has cruzado todos los niveles!";gStrYouWinLevelTxt="Hacer clic en PROSEGUIR para acceder al siguiente nivel...";gStrStart="JUGAR";gStrLevel="Nivel";gStrScore="Puntaje";gStrLook="Observe las ubicaciones de las bolas y intentar recordarlas";gStrMsgPlayer="colocar las bolas en el ábaco y en el orden correcto.";gStrClickStart="Hacer clic en JUGAR para empezar";gStrTitleGame="juego del ábaco";gStrCheck="RESULTADOS";gStrTryAgain="VOLVER A JUGAR";gStrPlayAgain="VOLVER A JUGAR";gStrContinue="PROSEGUIR";gStrLost="Perdido!";gStrBallFound="bola correctamente colocada";gStrBallsFound="bolas correctamente colocadas";}else if(lang=='fr'){gStrYouWin="*********&nbsp;&nbsp;Félicitations!!!&nbsp;&nbsp;**********";gStrYouWinLevel="Félicitations!  Vous avez gagné!";gStrYouWinTxt="Vous avez franchi tous les niveaux!";gStrYouWinLevelTxt="Cliquez sur CONTINUER pour aller au niveau suivant...";gStrStart="JOUER";gStrLevel="Niveau";gStrScore="Score";gStrLook="Observez la suite de boules et mémorisez-la";gStrMsgPlayer="Vous devez positionner les boules sur le boulier dans le bon ordre";gStrClickStart="Cliquez sur JOUER pour commencer";gStrTitleGame="Jeu du boulier";gStrCheck="RÉSULTATS";gStrTryAgain="REJOUER";gStrPlayAgain="REJOUER";gStrContinue="CONTINUER";gStrLost="Vous avez perdu!";gStrBallFound="boule correctement positionnée";gStrBallsFound="boules correctement positionnées";}
function set_level(){switch(gLevel){case 1:gBalls=5;gameDurationSeconds=10;break;case 2:gBalls=5;gameDurationSeconds=6;break;case 3:gBalls=6;gameDurationSeconds=10;break;case 4:gBalls=8;gameDurationSeconds=15;break;case 5:gBalls=10;gameDurationSeconds=25;break;case 6:gBalls=12;gameDurationSeconds=30;break;case 7:gBalls=14;gameDurationSeconds=40;break;default:gBalls=5;gameDurationSeconds=6;break;}
if(gBalls<6){gBallsWidth=Math.floor(100/gBalls)-2;}else{gBallsWidth=Math.floor(100/gBalls)-0.5;}
gAllBallsWidth=gBallsWidth*gBalls;}
function shuffle(a){var j,x,i;for(i=a.length-1;i>0;i--){j=Math.floor(Math.random()*(i+1));x=a[i];a[i]=a[j];a[j]=x;}
return a;}
function nb_aleatoire(limit){var random=Math.floor(Math.random()*limit);return random;}
function show_intro(){var html='<h3 class="intro_game_title">'+gStrTitleGame+'</h3>';html+='<div class="card"><img src="'+pathImages+'/intro.png" class="image_intro"/></div>';html+='<p class="intro_game_subtitle">'+gStrClickStart+'</p>';$("#board #cards").html(html);}
function fix_height(){gBallsHeight=$("#card_int_0").innerWidth();$('.card_int').each(function(){$(this).css("height",gBallsHeight+"px");$(this).css("width",gBallsHeight+"px");$(this).parent().css("height",gBallsHeight+"px");$("#abacus_support,.abacus_support,#block_card_2").css("height",gBallsHeight+"px");});}
function construct_grid(){arrayRandom.length=0;arrayShuffle.length=0;for(var i=0;i<gBalls;i++){var nb_aleat=nb_aleatoire(gBallsImages);arrayRandom[i]=nb_aleat;arrayShuffle[i]=nb_aleat;}
var html='<div id="block_card_1" ><div class="abacus_support" style="background-image:url(\''+pathImages+'/support.png\');">';for(var i=0;i<arrayRandom.length;i++){html+='<div class="card" style="width:'+gBallsWidth+'%;"><div class="card_int" id="card_int_'+i+'"><img src="'+pathImages+'/image'+arrayRandom[i]+'.png" imageposition="'+i+'" imageid="'+arrayRandom[i]+'" /></div></div>';}
html+='</div></div>';$("#board #cards").html(html);setTimeout(function(){fix_height();},10);}
function active_balls_for_player(){arrayShuffle=shuffle(arrayShuffle);var html='<div id="block_card_1"><div id="abacus_support" class="connectedSortable" style="background-image:url(\''+pathImages+'/support.png\');"></div></div>';html+='<div id="block_card_2" class="connectedSortable">';for(var i=0;i<arrayShuffle.length;i++){html+='<div class="card" style="width:'+gBallsWidth+'%;"><div class="card_int" id="card_int_'+i+'"><img src="'+pathImages+'/image'+arrayShuffle[i]+'.png" imageposition="'+i+'" imageid="'+arrayShuffle[i]+'" /></div></div>';}
html+='</div>';$("#board #cards").html(html);$('#player_msg_txt').html('<span class="long_text">'+gStrMsgPlayer+'</span>');setTimeout(function(){fix_height();},10);$("#abacus_support,#block_card_2").sortable({connectWith:".connectedSortable"}).disableSelection();$('#player_button').html(gStrCheck).show();$('#player_button').on('touchstart',function(){detectTap=true;});$('#player_button').on('touchmove',function(){detectTap=false;});$('#player_button').off().on('click touchend',function(e){if(e.type=="click"){detectTap=true;}
if(detectTap){e.preventDefault();e.stopPropagation();show_player_results();}
detectTap=false;});}
function show_player_results(){$("#abacus_support,#block_card_2").sortable("destroy");var html='<div class="abacus_support" style="background-image:url(\''+pathImages+'/support.png\');">';for(var i=0;i<arrayRandom.length;i++){html+='<div class="card" style="width:'+gBallsWidth+'%;"><div class="card_int" id="card_int_'+i+'"><img src="'+pathImages+'/image'+arrayRandom[i]+'.png" imageposition="'+i+'" imageid="'+arrayRandom[i]+'" /></div></div>';}
html+='</div>';$("#board #cards #block_card_2").html(html);arrayPlayer.length=0;arrayPlayerIds.lenght=0;var index=0;$("#block_card_1 .card_int img").each(function(){arrayPlayer[index]=$(this).attr("imageId");arrayPlayerIds[index]=$(this).attr("imageposition");index++;});var playerHasPositionedAllBalls=false;if(arrayPlayer.length==arrayRandom.length){playerHasPositionedAllBalls=true;for(var j=0;j<arrayPlayer.length;j++){if(arrayPlayer[j]==arrayRandom[j]){gCountGoodPayerBalls++;$("#card_int_"+arrayPlayerIds[j]).addClass("good");}else{$("#card_int_"+arrayPlayerIds[j]).addClass("wrong");}}}
if(playerHasPositionedAllBalls&&(gCountGoodPayerBalls==gBalls)){gPlayerWin=true;gScore+=gCountGoodPayerBalls;gLevel++;$('#score span').html("Score: <span style='font-weight:600;'>"+gScore+"</span> /"+gTotalScore);if(gLevel>gTotalLevel){$('#player_msg_txt').html('<span class="long_text"><span style="font-weight:700">'+gStrYouWin+'</span>'+gStrYouWinTxt+'</span>');$('#player_button').html(gStrPlayAgain).show();}else{$('#player_msg_txt').html('<span class="long_text"><span style="font-weight:700">'+gStrYouWinLevel+'</span>'+gStrYouWinLevelTxt+'</span>');$('#player_button').html(gStrContinue).show();}
$('#player_button').on('touchstart',function(){detectTap=true;});$('#player_button').on('touchmove',function(){detectTap=false;});$('#player_button').off().on('click touchend',function(e){if(e.type=="click"){detectTap=true;}
if(detectTap){e.preventDefault();e.stopPropagation();new_game();}
detectTap=false;});}else{if(!playerHasPositionedAllBalls){$('#player_msg_txt').html('<span class="long_text"><span style="font-weight:700">'+gStrLost+'</span></span>');}else if(gCountGoodPayerBalls==0||gCountGoodPayerBalls==1){$('#player_msg_txt').html('<span class="long_text"><span style="font-weight:700">'+gStrLost+'</span> '+gCountGoodPayerBalls+' '+gStrBallFound+' /'+gBalls+'</span>');}else{$('#player_msg_txt').html('<span class="long_text"><span style="font-weight:700">'+gStrLost+'</span> '+gCountGoodPayerBalls+' '+gStrBallsFound+' /'+gBalls+'</span>');}
$('#player_button').html(gStrTryAgain).show();$('#player_button').on('touchstart',function(){detectTap=true;});$('#player_button').on('touchmove',function(){detectTap=false;});$('#player_button').off().on('click touchend',function(e){if(e.type=="click"){detectTap=true;}
if(detectTap){e.preventDefault();e.stopPropagation();new_game();}
detectTap=false;});}}
function new_game(){arrayRandom=new Array();arrayPlayer=new Array();arrayPlayerIds=new Array();gCountPayerSquares=0;gCountGoodPayerBalls=0;gPlayerWin=false;if(gLevel>gTotalLevel){gLevel=1;gScore=0;}
init();start();}
function init(){set_level();show_intro();$('#level span').html(gStrLevel+": <span style='font-weight:600'>"+gLevel+"</span> /"+gTotalLevel);$('#score span').html(gStrScore+": <span style='font-weight:600'>"+gScore+"</span> /"+gTotalScore);$('#player_msg_txt').html("<span class='long_text'>"+gStrLook+"</span>");$('#player_button').html(gStrStart);$('#countdown').html("");$('#countdown').countdown({timestamp:new Date(),hideHours:true,showOnly:true,forceStop:false,callback:function(){}});}
function start(){construct_grid();var dateNow=new Date();var tsNow=dateNow.getTime();var tsMax=tsNow+gameDurationSeconds*1000;var dateMax=new Date(tsMax);$('#countdown').html("");$('#countdown').countdown({timestamp:dateMax,hideHours:true,showOnly:false,forceStop:false,callback:function(days,hours,minutes,seconds){active_balls_for_player();}});$("#player_button").hide();}
$('#player_button').on('touchstart',function(){detectTap=true;});$('#player_button').on('touchmove',function(){detectTap=false;});$('#player_button').off().on('click touchend',function(e){if(e.type=="click"){detectTap=true;}
if(detectTap){e.preventDefault();e.stopPropagation();start();}
detectTap=false;});init();return $(this);};})(jQuery);
